FROM openjdk:11-slim

#Add volume pointing to /tmp
VOLUME /tmp

#Copy unpackaged application to new container
WORKDIR application
COPY --from=build application/dependencies ./
COPY --from=build application/spring-boot-loader ./
COPY --from=build application/snapshot-dependencies ./
COPY --from=build application/application ./

#execute the application
ENTRYPOINT ["java", "crk.interview.xmens.XMensApplication"]