spring:
  application:
    name: xmens
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        outBoundMutant:
          destination: MUTANT
          content-type: application/json
        inBoundMutant:
          destination: MUTANT
          content-type: application/json
          group: xmens
      kafka:
        binder:
          brokers: kafka

redis:
  port: 6379
  host: sbs_redis

logging:
  level:
    org:
      springframework:
        cache: INFO

management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "health,env,info,refresh"
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    env:
      enabled: true
    health:
      enabled: true
    refresh:
      enabled: true

amazon:
  dynamodb:
    host: dynamodb-local
    port: 8000
  aws:
    accesskey: "onekey"
    secretkey: "secondkey"

aggregation:
  key: "aggregation"

server:
  port: 8081